/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_run"];
        put?: never;
        post?: never;
        delete: operations["delete_run"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/confirm-contract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["confirm_contract"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/confirm-revision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["confirm_revision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/select-findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["select_findings"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddOverrideOperation */
        AddOverrideOperation: {
            /**
             * Dimension
             * @enum {string}
             */
            dimension: "eligibility" | "receipt_requirement" | "approval_requirement" | "claim_cap_minor" | "daily_category_cap_minor";
            /** Finding Ids */
            finding_ids: string[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "add_override";
            /** Rule Id */
            rule_id: string;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Target Rule Id */
            target_rule_id: string;
        };
        /** AddRuleOperation */
        AddRuleOperation: {
            /** Finding Ids */
            finding_ids: string[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "add_rule";
            rule: components["schemas"]["RevisionRuleDraft"];
            /** Rule Id */
            rule_id: string;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
        };
        /** ArtifactRef */
        ArtifactRef: {
            /** Artifact Sha256 */
            artifact_sha256: string;
            /**
             * Artifact Type
             * @enum {string}
             */
            artifact_type: "policy_document" | "policy_ir" | "policy_contract" | "scenario_suite" | "evaluation_report" | "finding_report" | "revision_proposal" | "regression_report" | "patch_acceptance_report" | "comparison_bundle" | "metrics_report" | "benchmark_manifest" | "benchmark_score" | "coverage_snapshot" | "run_manifest";
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Semantic Sha256 */
            semantic_sha256: string;
        };
        /** ArtifactSummary */
        ArtifactSummary: {
            artifact: components["schemas"]["ArtifactRef"];
            /**
             * Item Count
             * @default null
             */
            item_count: number | null;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Title */
            title: string;
        };
        /**
         * AssertionContent
         * @description Typed assertion content, without oracle origins or private label references.
         */
        AssertionContent: {
            /** Assertion Id */
            assertion_id: string;
            /**
             * Dimension
             * @enum {string}
             */
            dimension: "eligibility" | "receipt_requirement" | "approval_requirement" | "claim_cap_minor" | "daily_category_cap_minor";
            /** Expected Value */
            expected_value: ("allow" | "deny") | ("required" | "not_required") | ("none" | "manager" | "director" | "finance") | number | ("COMPLIANT" | "NONCOMPLIANT");
            /**
             * Operator
             * @enum {string}
             */
            operator: "eq" | "neq" | "lte" | "gte";
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /**
             * Target Kind
             * @enum {string}
             */
            target_kind: "effect_value" | "compliance_value";
        };
        /** AssertionCounts */
        AssertionCounts: {
            /**
             * Error
             * @default 0
             */
            error: number;
            /**
             * Failed
             * @default 0
             */
            failed: number;
            /**
             * Inconclusive
             * @default 0
             */
            inconclusive: number;
            /**
             * Passed
             * @default 0
             */
            passed: number;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
        };
        /** AssertionTransitionCounts */
        AssertionTransitionCounts: {
            /**
             * Fail To Fail
             * @default 0
             */
            fail_to_fail: number;
            /**
             * Fail To Pass
             * @default 0
             */
            fail_to_pass: number;
            /**
             * Inconclusive Or Error
             * @default 0
             */
            inconclusive_or_error: number;
            /**
             * Pass To Fail
             * @default 0
             */
            pass_to_fail: number;
            /**
             * Pass To Pass
             * @default 0
             */
            pass_to_pass: number;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
        };
        /** ComplianceResult */
        ComplianceResult: {
            /**
             * Dimension
             * @enum {string}
             */
            dimension: "receipt_requirement" | "approval_requirement" | "claim_cap_minor" | "daily_category_cap_minor";
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /**
             * Status
             * @enum {string}
             */
            status: "COMPLIANT" | "NONCOMPLIANT" | "NOT_APPLICABLE" | "INCONCLUSIVE" | "ERROR";
        };
        /**
         * ConfirmContractRequest
         * @description Confirm a server-held baseline by identity/hash and submit reviewed intent.
         *
         *     The coordinator checks both anchors against the stored provisional baseline;
         *     the browser cannot replace the compiled rules or unsupported-clause mappings.
         */
        ConfirmContractRequest: {
            /**
             * Baseline Policy Id
             * @default null
             */
            baseline_policy_id: string | null;
            /**
             * Baseline Policy Sha256
             * @description Artifact SHA256 of the exact server-held baseline PolicyIR.
             * @default null
             */
            baseline_policy_sha256: string | null;
            /**
             * Decision
             * @enum {string}
             */
            decision: "confirm" | "reject";
            /**
             * Invariants
             * @default []
             */
            invariants: components["schemas"]["InvariantSummary"][];
            /**
             * Required Dimensions
             * @default []
             */
            required_dimensions: ("eligibility" | "receipt_requirement" | "approval_requirement" | "claim_cap_minor" | "daily_category_cap_minor")[];
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
        };
        /** ConfirmRevisionRequest */
        ConfirmRevisionRequest: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "confirm" | "reject";
            /** Proposal Id */
            proposal_id: string;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
        };
        /** ContractConfirmation */
        ContractConfirmation: {
            /** Baseline Policy Id */
            baseline_policy_id: string;
            /**
             * Baseline Policy Sha256
             * @description Artifact SHA256 of the exact server-held baseline PolicyIR.
             */
            baseline_policy_sha256: string;
            /** Document Sha256 */
            document_sha256: string;
            /** Invariants */
            invariants: components["schemas"]["InvariantSummary"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "contract";
            /** Required Dimensions */
            required_dimensions: ("eligibility" | "receipt_requirement" | "approval_requirement" | "claim_cap_minor" | "daily_category_cap_minor")[];
            /** Rules */
            rules: components["schemas"]["RuleSummary"][];
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
        };
        /** CoverageCounters */
        CoverageCounters: {
            /**
             * Covered Invariants
             * @default 0
             */
            covered_invariants: number;
            /**
             * Covered Predicate Branches
             * @default 0
             */
            covered_predicate_branches: number;
            /**
             * Covered Rules
             * @default 0
             */
            covered_rules: number;
            /**
             * Scenario Count
             * @default 0
             */
            scenario_count: number;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /**
             * Total Invariants
             * @default 0
             */
            total_invariants: number;
            /**
             * Total Predicate Branches
             * @default 0
             */
            total_predicate_branches: number;
            /**
             * Total Rules
             * @default 0
             */
            total_rules: number;
        };
        /** CreateRunRequest */
        CreateRunRequest: {
            /**
             * Non Confidential Confirmed
             * @default false
             */
            non_confidential_confirmed: boolean;
            /**
             * Sample Id
             * @default null
             */
            sample_id: string | null;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "pasted_text" | "bundled_sample";
            /**
             * Text
             * @default null
             */
            text: string | null;
            /** Title */
            title: string;
        };
        /** CreateRunResponse */
        CreateRunResponse: {
            /** Run Id */
            run_id: string;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
        };
        /** DeleteRunResponse */
        DeleteRunResponse: {
            /**
             * Deleted
             * @default true
             * @constant
             */
            deleted: true;
            /** Run Id */
            run_id: string;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
        };
        /** DimensionResult */
        DimensionResult: {
            /**
             * Applicable Rule Ids
             * @default []
             */
            applicable_rule_ids: string[];
            /**
             * Conflicting Values
             * @default []
             */
            conflicting_values: (("allow" | "deny") | ("required" | "not_required") | ("none" | "manager" | "director" | "finance") | number)[];
            /**
             * Dimension
             * @enum {string}
             */
            dimension: "eligibility" | "receipt_requirement" | "approval_requirement" | "claim_cap_minor" | "daily_category_cap_minor";
            /**
             * Overridden Rule Ids
             * @default []
             */
            overridden_rule_ids: string[];
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /**
             * Status
             * @enum {string}
             */
            status: "VALUE" | "GAP" | "NOT_APPLICABLE" | "CONFLICT" | "INCONCLUSIVE" | "ERROR";
            /**
             * Unsupported Clause Ids
             * @default []
             */
            unsupported_clause_ids: string[];
            /**
             * Value
             * @default null
             */
            value: ("allow" | "deny") | ("required" | "not_required") | ("none" | "manager" | "director" | "finance") | number | null;
        };
        /** Effect */
        Effect: {
            /**
             * Dimension
             * @enum {string}
             */
            dimension: "eligibility" | "receipt_requirement" | "approval_requirement" | "claim_cap_minor" | "daily_category_cap_minor";
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Value */
            value: ("allow" | "deny") | ("required" | "not_required") | ("none" | "manager" | "director" | "finance") | number;
        };
        /** EffectStateCounts */
        EffectStateCounts: {
            /**
             * Conflict
             * @default 0
             */
            CONFLICT: number;
            /**
             * Error
             * @default 0
             */
            ERROR: number;
            /**
             * Gap
             * @default 0
             */
            GAP: number;
            /**
             * Inconclusive
             * @default 0
             */
            INCONCLUSIVE: number;
            /**
             * Not Applicable
             * @default 0
             */
            NOT_APPLICABLE: number;
            /**
             * Value
             * @default 0
             */
            VALUE: number;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
        };
        /** FindingDecision */
        FindingDecision: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "accept" | "reject";
            /** Finding Id */
            finding_id: string;
            /**
             * Reviewer Severity
             * @default null
             */
            reviewer_severity: ("low" | "medium" | "high" | "critical") | null;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
        };
        /** FindingSummary */
        FindingSummary: {
            /**
             * Dimension
             * @enum {string}
             */
            dimension: "eligibility" | "receipt_requirement" | "approval_requirement" | "claim_cap_minor" | "daily_category_cap_minor";
            /** Finding Id */
            finding_id: string;
            /**
             * Finding Type
             * @enum {string}
             */
            finding_type: "structural_gap" | "conflict" | "intent_breach" | "regression" | "unsupported_clause" | "potential_loophole";
            /**
             * Review Status
             * @enum {string}
             */
            review_status: "pending" | "accepted" | "rejected";
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /**
             * Severity
             * @default null
             */
            severity: ("low" | "medium" | "high" | "critical") | null;
            /** Summary */
            summary: string;
            /** Witness Count */
            witness_count: number;
        };
        /** FindingsConfirmation */
        FindingsConfirmation: {
            /** Finding Ids */
            finding_ids: string[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "findings";
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
        };
        /** HealthResponse */
        HealthResponse: {
            /** Engine Version */
            engine_version: string;
            /** Provider Configured */
            provider_configured: boolean;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
        };
        /**
         * HoldoutEvidenceSummary
         * @description The only holdout evidence shape: aggregate counts with no case identifiers.
         *
         *     Projectors must route all private clauses, rejections and traces here, never
         *     into the visible evidence collections or free-text summaries/events.
         */
        HoldoutEvidenceSummary: {
            baseline_effect_states?: components["schemas"]["EffectStateCounts"];
            /**
             * Partition
             * @default holdout
             * @constant
             */
            partition: "holdout";
            /**
             * Rejected Rule Count
             * @default 0
             */
            rejected_rule_count: number;
            /**
             * Rejected Scenario Count
             * @default 0
             */
            rejected_scenario_count: number;
            /** @default null */
            revised_effect_states: components["schemas"]["EffectStateCounts"] | null;
            /**
             * Scenario Count
             * @default 0
             */
            scenario_count: number;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /**
             * Unsupported Clause Count
             * @default 0
             */
            unsupported_clause_count: number;
        };
        /** InputHashes */
        InputHashes: {
            /** Contract Sha256 */
            contract_sha256: string;
            /** Engine Sha256 */
            engine_sha256: string;
            /** Policy Sha256 */
            policy_sha256: string;
            /** Run Manifest Sha256 */
            run_manifest_sha256: string;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Suite Sha256 */
            suite_sha256: string;
        };
        /**
         * InvariantSummary
         * @description Session intent for review/editing; no gold or mechanical oracle metadata.
         */
        InvariantSummary: {
            assertion: components["schemas"]["AssertionContent"];
            /** Description */
            description: string;
            /** Invariant Id */
            invariant_id: string;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /**
             * Severity
             * @enum {string}
             */
            severity: "low" | "medium" | "high" | "critical";
            /** When */
            when: components["schemas"]["Predicate"][];
        };
        /** OverrideRef */
        OverrideRef: {
            /**
             * Dimension
             * @enum {string}
             */
            dimension: "eligibility" | "receipt_requirement" | "approval_requirement" | "claim_cap_minor" | "daily_category_cap_minor";
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Target Rule Id */
            target_rule_id: string;
        };
        /** PatchAcceptanceCounts */
        PatchAcceptanceCounts: {
            /**
             * Baseline Gap Conflict Inconclusive Or Error
             * @default 0
             */
            baseline_gap_conflict_inconclusive_or_error: number;
            /**
             * Fixed Target Findings
             * @default 0
             */
            fixed_target_findings: number;
            /**
             * Holdout Regressions
             * @default 0
             */
            holdout_regressions: number;
            /**
             * New Failures Outside Targets
             * @default 0
             */
            new_failures_outside_targets: number;
            /**
             * Protected Regressions
             * @default 0
             */
            protected_regressions: number;
            /**
             * Revised Gap Conflict Inconclusive Or Error
             * @default 0
             */
            revised_gap_conflict_inconclusive_or_error: number;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /**
             * Target Findings
             * @default 0
             */
            target_findings: number;
            /**
             * Unrelated Rule Changes
             * @default 0
             */
            unrelated_rule_changes: number;
        };
        /** PatchAcceptanceReport */
        PatchAcceptanceReport: {
            /** All Target Findings Fixed */
            all_target_findings_fixed: boolean;
            baseline_inputs: components["schemas"]["InputHashes"];
            counts?: components["schemas"]["PatchAcceptanceCounts"];
            /** Holdout Not Worse */
            holdout_not_worse: boolean;
            /** No Increase In Gap Conflict Inconclusive Or Error */
            no_increase_in_gap_conflict_inconclusive_or_error: boolean;
            /** Patch Accepted */
            patch_accepted: boolean;
            revised_inputs: components["schemas"]["InputHashes"];
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Suite Hash Matches */
            suite_hash_matches: boolean;
            /** Unrelated Rules Unchanged */
            unrelated_rules_unchanged: boolean;
            /** Zero New Failures Outside Targets */
            zero_new_failures_outside_targets: boolean;
            /** Zero Protected Regressions */
            zero_protected_regressions: boolean;
        };
        /** Predicate */
        Predicate: {
            /** Field */
            field: ("employee_role" | "expense_category" | "amount_minor" | "destination_type" | "booking_days_before" | "receipt_present" | "approval_roles_present" | "prior_same_day_category_spend_minor") | "daily_category_total_minor";
            /**
             * Operator
             * @enum {string}
             */
            operator: "eq" | "neq" | "in" | "not_in" | "lt" | "lte" | "gt" | "gte" | "contains";
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Value */
            value: string | number | boolean | string[];
        };
        /** PredicateResult */
        PredicateResult: {
            /** Matched */
            matched: boolean;
            /** Predicate Index */
            predicate_index: number;
            /** Rule Id */
            rule_id: string;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
        };
        /** PublicComparisonMetrics */
        PublicComparisonMetrics: {
            acceptance: components["schemas"]["PatchAcceptanceReport"];
            assertion_transition_counts: components["schemas"]["AssertionTransitionCounts"];
            baseline: components["schemas"]["PublicMetrics"];
            /** New Failures Outside Targets */
            new_failures_outside_targets: number;
            /** Patch Accepted */
            patch_accepted: boolean;
            /** Protected Regressions */
            protected_regressions: number;
            revised: components["schemas"]["PublicMetrics"];
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
        };
        /** PublicError */
        PublicError: {
            /**
             * Code
             * @enum {string}
             */
            code: "INVALID_INPUT" | "INVALID_STATE" | "INVALID_POLICY" | "INVALID_CITATION" | "MALFORMED_MODEL_OUTPUT" | "PROVIDER_UNAVAILABLE" | "COVERAGE_LIMIT_EXCEEDED" | "HASH_MISMATCH" | "REVISION_INVALID" | "PROSE_COMPILE_MISMATCH" | "RUN_NOT_FOUND" | "INTERNAL_ERROR";
            /**
             * Error Id
             * @default null
             */
            error_id: string | null;
            /** Message */
            message: string;
            /**
             * Retryable
             * @default false
             */
            retryable: boolean;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
        };
        /** PublicMetrics */
        PublicMetrics: {
            /**
             * Assertion Pass Percent
             * @default null
             */
            assertion_pass_percent: number | null;
            assertions: components["schemas"]["AssertionCounts"];
            effect_states: components["schemas"]["EffectStateCounts"];
            /** Scenario Count */
            scenario_count: number;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Unique Finding Count */
            unique_finding_count: number;
        };
        /**
         * RejectionEvidence
         * @description Visible rejection; source_spans is empty when no policy source exists.
         */
        RejectionEvidence: {
            /**
             * Disposition
             * @enum {string}
             */
            disposition: "excluded" | "merged_duplicate" | "rule_set_rejected";
            /** Item Id */
            item_id: string;
            /**
             * Item Kind
             * @enum {string}
             */
            item_kind: "rule" | "scenario";
            /**
             * Partition
             * @default visible
             * @constant
             */
            partition: "visible";
            /**
             * Reason Code
             * @enum {string}
             */
            reason_code: "invalid_citation" | "unsupported_vocabulary" | "unsupported_logic" | "invalid_rule" | "dangling_override" | "override_cycle" | "invalid_facts" | "invalid_assertion" | "duplicate" | "budget_exceeded" | "incompatible_assertions";
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Source Spans */
            source_spans: components["schemas"]["SourceSpan"][];
        };
        /** ReplaceRuleOperation */
        ReplaceRuleOperation: {
            /** Expected Revision */
            expected_revision: number;
            /** Finding Ids */
            finding_ids: string[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "replace_rule";
            rule: components["schemas"]["RevisionRuleDraft"];
            /** Rule Id */
            rule_id: string;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
        };
        /** RevisionConfirmation */
        RevisionConfirmation: {
            /** Draft Policy Wording */
            draft_policy_wording: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "revision";
            /** Operations */
            operations: components["schemas"]["RevisionOperationSummary"][];
            /** Proposal Id */
            proposal_id: string;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
        };
        /**
         * RevisionOperationSummary
         * @description Authoritative typed operation with the affected baseline rule for comparison.
         */
        RevisionOperationSummary: {
            /** @default null */
            before: components["schemas"]["RuleSummary"] | null;
            /** Operation */
            operation: components["schemas"]["AddRuleOperation"] | components["schemas"]["ReplaceRuleOperation"] | components["schemas"]["AddOverrideOperation"];
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
        };
        /**
         * RevisionRuleDraft
         * @description Proposed rule content. Confirmation provenance is assigned only on application.
         */
        RevisionRuleDraft: {
            /** Description */
            description: string;
            /** Effects */
            effects: components["schemas"]["Effect"][];
            /**
             * Overrides
             * @default []
             */
            overrides: components["schemas"]["OverrideRef"][];
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** When */
            when: components["schemas"]["Predicate"][];
        };
        /**
         * RuleSummary
         * @description Review of a server-held baseline rule with source citations.
         */
        RuleSummary: {
            /** Citations */
            citations: components["schemas"]["TextRuleProvenance"][];
            /**
             * Confidence Percent
             * @default null
             */
            confidence_percent: number | null;
            /** Description */
            description: string;
            /** Effects */
            effects: components["schemas"]["Effect"][];
            /**
             * Overrides
             * @default []
             */
            overrides: components["schemas"]["OverrideRef"][];
            /** Revision */
            revision: number;
            /** Rule Id */
            rule_id: string;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** When */
            when: components["schemas"]["Predicate"][];
        };
        /** RunEvent */
        RunEvent: {
            /** Action Summary */
            action_summary: string;
            /** @default null */
            artifact: components["schemas"]["ArtifactRef"] | null;
            /**
             * Error Id
             * @default null
             */
            error_id: string | null;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /**
             * Stage
             * @enum {string}
             */
            stage: "queued" | "ingesting" | "extracting" | "awaiting_contract" | "generating_initial_tests" | "provisional_execution" | "targeting_coverage" | "freezing_suite" | "baseline_execution" | "analyzing" | "awaiting_finding_review" | "drafting_revision" | "awaiting_revision_confirmation" | "applying_revision" | "retesting" | "complete" | "completed_no_findings" | "completed_no_revision" | "contract_rejected" | "revision_rejected" | "coverage_limit_exceeded" | "failed";
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** RunView */
        RunView: {
            /**
             * Allowed Actions
             * @default []
             */
            allowed_actions: ("confirm_contract" | "reject_contract" | "select_findings" | "confirm_revision" | "reject_revision" | "delete_run")[];
            /**
             * Artifacts
             * @default []
             */
            artifacts: components["schemas"]["ArtifactSummary"][];
            /** @default null */
            baseline_metrics: components["schemas"]["PublicMetrics"] | null;
            /** @default null */
            comparison_metrics: components["schemas"]["PublicComparisonMetrics"] | null;
            coverage?: components["schemas"]["CoverageCounters"];
            /**
             * Decision At
             * @default null
             */
            decision_at: string | null;
            /** @default null */
            error: components["schemas"]["PublicError"] | null;
            /**
             * Events
             * @default []
             */
            events: components["schemas"]["RunEvent"][];
            /**
             * Findings
             * @default []
             */
            findings: components["schemas"]["FindingSummary"][];
            /** @default null */
            holdout_evidence: components["schemas"]["HoldoutEvidenceSummary"] | null;
            /**
             * Mode
             * @enum {string}
             */
            mode: "live" | "cached";
            /**
             * Pending Confirmation
             * @default null
             */
            pending_confirmation: (components["schemas"]["ContractConfirmation"] | components["schemas"]["FindingsConfirmation"] | components["schemas"]["RevisionConfirmation"]) | null;
            /**
             * Rejections
             * @default []
             */
            rejections: components["schemas"]["RejectionEvidence"][];
            /** Run Id */
            run_id: string;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /**
             * Stage
             * @enum {string}
             */
            stage: "queued" | "ingesting" | "extracting" | "awaiting_contract" | "generating_initial_tests" | "provisional_execution" | "targeting_coverage" | "freezing_suite" | "baseline_execution" | "analyzing" | "awaiting_finding_review" | "drafting_revision" | "awaiting_revision_confirmation" | "applying_revision" | "retesting" | "complete" | "completed_no_findings" | "completed_no_revision" | "contract_rejected" | "revision_rejected" | "coverage_limit_exceeded" | "failed";
            /**
             * Terminal Status
             * @default null
             */
            terminal_status: ("complete" | "completed_no_findings" | "completed_no_revision" | "contract_rejected" | "revision_rejected" | "coverage_limit_exceeded" | "failed") | null;
            /**
             * Traces
             * @default []
             */
            traces: components["schemas"]["VisibleTraceSummary"][];
            /**
             * Unsupported Clauses
             * @default []
             */
            unsupported_clauses: components["schemas"]["UnsupportedClauseEvidence"][];
        };
        /** SelectFindingsRequest */
        SelectFindingsRequest: {
            /** Decisions */
            decisions: components["schemas"]["FindingDecision"][];
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
        };
        /** SourceSpan */
        SourceSpan: {
            /** End */
            end: number;
            /** Page */
            page: number;
            /** Quote */
            quote: string;
            /** Quote Sha256 */
            quote_sha256: string;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /**
             * Section
             * @default null
             */
            section: string | null;
            /** Start */
            start: number;
        };
        /** TextRuleProvenance */
        TextRuleProvenance: {
            /** Citation Id */
            citation_id: string;
            /**
             * Kind
             * @default text_citation
             * @constant
             */
            kind: "text_citation";
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            span: components["schemas"]["SourceSpan"];
        };
        /**
         * UnsupportedClauseEvidence
         * @description Visible-policy evidence only; private clauses contribute to holdout counts.
         */
        UnsupportedClauseEvidence: {
            /** Affected Dimensions */
            affected_dimensions: ("eligibility" | "receipt_requirement" | "approval_requirement" | "claim_cap_minor" | "daily_category_cap_minor")[];
            /** Clause Id */
            clause_id: string;
            /**
             * Disposition
             * @enum {string}
             */
            disposition: "pending_review" | "retained_inconclusive" | "excluded";
            /**
             * Partition
             * @default visible
             * @constant
             */
            partition: "visible";
            /**
             * Reason Code
             * @enum {string}
             */
            reason_code: "unsupported_vocabulary" | "unsupported_logic" | "ambiguous_language" | "invalid_citation" | "unsupported_aggregation" | "unsupported_currency";
            /**
             * Review Status
             * @default provisional
             * @enum {string}
             */
            review_status: "provisional" | "session_confirmed";
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            span: components["schemas"]["SourceSpan"];
            /**
             * When Hint
             * @default null
             */
            when_hint: components["schemas"]["Predicate"][] | null;
        };
        /**
         * VisibleTraceSummary
         * @description Visible execution evidence, never facts, assertion answers, or holdout rows.
         */
        VisibleTraceSummary: {
            /** Compliance Values */
            compliance_values: components["schemas"]["ComplianceResult"][];
            /** Fired Rule Ids */
            fired_rule_ids: string[];
            /**
             * Partition
             * @default visible
             * @constant
             */
            partition: "visible";
            /**
             * Phase
             * @enum {string}
             */
            phase: "baseline" | "revised";
            /** Predicate Results */
            predicate_results: components["schemas"]["PredicateResult"][];
            /** Resolved Effects */
            resolved_effects: components["schemas"]["DimensionResult"][];
            /** Scenario Id */
            scenario_id: string;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Source Citations */
            source_citations: components["schemas"]["SourceSpan"][];
            /** Trace Sha256 */
            trace_sha256: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Structured public application error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["PublicError"];
                    };
                };
            };
            /** @description Structured public application error */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["PublicError"];
                    };
                };
            };
        };
    };
    create_run: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunRequest"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateRunResponse"];
                };
            };
            /** @description Structured public application error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["PublicError"];
                    };
                };
            };
            /** @description Structured public application error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["PublicError"];
                    };
                };
            };
            /** @description Structured public application error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["PublicError"];
                    };
                };
            };
            /** @description Structured public application error */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["PublicError"];
                    };
                };
            };
        };
    };
    get_run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Structured public application error */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["PublicError"];
                    };
                };
            };
            /** @description Structured public application error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["PublicError"];
                    };
                };
            };
            /** @description Structured public application error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["PublicError"];
                    };
                };
            };
        };
    };
    delete_run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteRunResponse"];
                };
            };
            /** @description Structured public application error */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["PublicError"];
                    };
                };
            };
            /** @description Structured public application error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["PublicError"];
                    };
                };
            };
            /** @description Structured public application error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["PublicError"];
                    };
                };
            };
        };
    };
    confirm_contract: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmContractRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Structured public application error */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["PublicError"];
                    };
                };
            };
            /** @description Structured public application error */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["PublicError"];
                    };
                };
            };
            /** @description Structured public application error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["PublicError"];
                    };
                };
            };
            /** @description Structured public application error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["PublicError"];
                    };
                };
            };
            /** @description Structured public application error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["PublicError"];
                    };
                };
            };
            /** @description Structured public application error */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["PublicError"];
                    };
                };
            };
        };
    };
    confirm_revision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmRevisionRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Structured public application error */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["PublicError"];
                    };
                };
            };
            /** @description Structured public application error */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["PublicError"];
                    };
                };
            };
            /** @description Structured public application error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["PublicError"];
                    };
                };
            };
            /** @description Structured public application error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["PublicError"];
                    };
                };
            };
            /** @description Structured public application error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["PublicError"];
                    };
                };
            };
            /** @description Structured public application error */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["PublicError"];
                    };
                };
            };
        };
    };
    select_findings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SelectFindingsRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Structured public application error */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["PublicError"];
                    };
                };
            };
            /** @description Structured public application error */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["PublicError"];
                    };
                };
            };
            /** @description Structured public application error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["PublicError"];
                    };
                };
            };
            /** @description Structured public application error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["PublicError"];
                    };
                };
            };
            /** @description Structured public application error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["PublicError"];
                    };
                };
            };
            /** @description Structured public application error */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["PublicError"];
                    };
                };
            };
        };
    };
}
