/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v2/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v2_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Run */
        post: operations["create_run_api_v2_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CreateRunRequest */
        CreateRunRequest: {
            /**
             * Fixture Name
             * @default completed
             * @enum {string}
             */
            fixture_name: "completed" | "partial_translation_unavailable";
            policy: components["schemas"]["RunPolicyInput"];
        };
        /**
         * ExecutionMode
         * @enum {string}
         */
        ExecutionMode: "fixture" | "recorded" | "live";
        /** HealthResponse */
        HealthResponse: {
            /**
             * Execution Mode
             * @default fixture
             * @constant
             */
            execution_mode: "fixture";
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** Persona */
        Persona: {
            /** Description */
            description: string;
            /** Display Name */
            display_name: string;
            /** Persona Id */
            persona_id: string;
        };
        /** PublicError */
        PublicError: {
            /** Detail */
            detail: string;
        };
        /**
         * PublicSandboxResult
         * @description Explicit public allowlist for Sandbox evidence.
         */
        PublicSandboxResult: {
            /** Configured Stakeholder Count */
            configured_stakeholder_count: number;
            /**
             * Errors
             * @default []
             */
            errors: string[];
            execution_mode: components["schemas"]["ExecutionMode"];
            /**
             * Limitations
             * @default []
             */
            limitations: string[];
            /**
             * Messages
             * @default []
             */
            messages: components["schemas"]["SandboxMessage"][];
            /** Observed Stakeholder Count */
            observed_stakeholder_count: number;
            /**
             * Personas
             * @default []
             */
            personas: components["schemas"]["Persona"][];
            /** Policy Text Sha256 */
            policy_text_sha256: string;
            /** Policy Title */
            policy_title: string;
            /** Policy Version */
            policy_version: string;
            /** Request Fingerprint */
            request_fingerprint: string;
            /** Request Id */
            request_id: string;
            /** Requested Stakeholder Count */
            requested_stakeholder_count: number;
            /** Run Id */
            run_id: string;
            /**
             * Schema Version
             * @default 2.0
             * @constant
             */
            schema_version: "2.0";
            /**
             * Sources
             * @default []
             */
            sources: components["schemas"]["SourceEvidence"][];
            status: components["schemas"]["SandboxStatus"];
        };
        /**
         * RunPolicyInput
         * @description The four policy fields accepted by the first-run milestone.
         */
        RunPolicyInput: {
            /** Agent Count */
            agent_count: number;
            /** Agent Seed */
            agent_seed: string;
            /** Description */
            description: string;
            /** Title */
            title: string;
        };
        /** SandboxMessage */
        SandboxMessage: {
            /** Content */
            content: string;
            /** Message Id */
            message_id: string;
            /** Persona Id */
            persona_id: string;
            /** Recorded At */
            recorded_at?: string | null;
            /**
             * Reply To Message Ids
             * @default []
             */
            reply_to_message_ids: string[];
            /** Round Number */
            round_number?: number | null;
            /** Sequence */
            sequence: number;
            /**
             * Source Refs
             * @default []
             */
            source_refs: string[];
            translation_status: components["schemas"]["TranslationStatus"];
        };
        /**
         * SandboxStatus
         * @enum {string}
         */
        SandboxStatus: "completed" | "partial" | "failed" | "cancelled";
        /** SourceEvidence */
        SourceEvidence: {
            /** Excerpt */
            excerpt: string;
            /** Record Id */
            record_id: string;
            /** Source Id */
            source_id: string;
            /** Title */
            title: string;
        };
        /**
         * TranslationStatus
         * @enum {string}
         */
        TranslationStatus: "original_english" | "translated" | "unavailable";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v2_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    create_run_api_v2_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicSandboxResult"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicError"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicError"];
                };
            };
        };
    };
}
